### ISSUE TITLE
Option to add oEmbed parameters

### ISSUE THREAD

**Issue by Autsider666** [Splidejs/splide-extension-video#10]
We're looking for an easy way to add oEmbed parameters to a video (in this case `playsinline` for vimeo), but there doesn't seem to be a way to add those at the moment without fighting the library itself. 

Any parameters added to the vimeo url are removed and the code only checks the iframe element (created by the code) for `data-vimeo-playsinline`, so it's quite hard.

**Comment by NaotoshiFujita** [comment]
I wanted to see how you fight the library, but I added a new option, `playerOptions`:
https://github.com/Splidejs/splide-extension-video#available-options

**Comment by Autsider666** [comment]
Thank you very much for another fast fix! 

Do you maybe have some kind of a donation button somewhere? We would love to show our support for your SplideJs libraries.
