### ISSUE TITLE
Setting height and width of youtube player

### ISSUE THREAD

**Issue by Autsider666** [Splidejs/splide-extension-video#12]
I've a follow up question after our [previous issue](https://github.com/Splidejs/splide-extension-video/issues/10):
Could it be possible to set the height/width of a youtube video player using the `playerOptions` functionality you added for the last issue?

The player options are added tot the `playerVars` when the youtube player is created, but the height/width [have to be configured in the root of the options](https://developers.google.com/youtube/player_parameters.html?playerVersion=HTML5#IFrame_Player_API).

**Comment by Autsider666** [comment]
It may be a bit of a weird request, so here's a short description of what we're trying to do:
We're trying to make the video's cover the whole slide (A bit like [this](https://jsfiddle.net/ohepworthbell/k72hbytr/) but with javascript), but we're having issues with the youtube iframe always having the same `width="640" height="360" ` (probably because the iframe wrapper element isn't added to the dom on time of creation).

We're trying to work around it by manualy setting the size of the player based on the size of the slide.

**Comment by NaotoshiFujita** [comment]
The extension applies this CSS to a youtube video:
```css
.splide__video iframe {
  width: 100%;
  height: 100%;
}
```
The iframe is initialized `640x360` but these values are ignored.
https://jsfiddle.net/px14u0jb/1/

**Comment by Autsider666** [comment]
We're trying to use the given width/height values from the iframe to calculate the screen ratio of the video, so 640x360 would always give us a 16/9 ratio, even when the video isn't. the `YT` library does get the right width/height from youtube, but it probably changes it to theses settings because the iframe wrapper hasn't been added to the DOM yet. This problem doesn't happen with vimeo by the way.

**Comment by NaotoshiFujita** [comment]
The width and height determine the player's dimension, not video itself. If the width and height are not provided(like this extension), the default values are used.

> width (number) – The width of the video player. The default value is 640.
> height (number) – The height of the video player. The default value is 360.

https://developers.google.com/youtube/iframe_api_reference

And you cannot get the video aspect ratio by the player API because it just creates and control a video **player**.

See this stackoverflow:
https://stackoverflow.com/questions/5010495/how-to-get-youtube-video-aspect-ratio
