### ISSUE TITLE
Can't run multiple vimeo video's over multiple splide elements in a single page

### ISSUE THREAD

**Issue by Autsider666** [Splidejs/splide-extension-video#13]
[Basically what the title describes](https://jsfiddle.net/kacjqwb8/)
Having multiple active slides with a vimeo video in them makes it impossible to start more than one of them. It seems to pause all the other vimeo video's

**Comment by NaotoshiFujita** [comment]
I think `autopause` solves the problem.

> `autopause`: Pause this video automatically when another one plays.

https://github.com/vimeo/player.js/
