### ISSUE TITLE
Slide autoplay with video autoplay is not working correctly

### ISSUE THREAD

**Issue by dannyvw** [Splidejs/splide-extension-video#2]
When configure the carousel and the video as autoplay then the carousel will loop without seeing the full video.

https://codepen.io/dannyvw/pen/VweeWPP

**Comment by NaotoshiFujita** [comment]
Okay. Closing this issue because autoplay is working correctly.

**Comment by dannyvw** [comment]
@NaotoshiFujita @Splidejs Is it possible to pause the autoplay on video:play?

**Comment by Splidejs** [comment]
Yes, it's possible through the Autoplay component.
```javascript
var Autoplay = splide.Components.Autoplay;
Autoplay.pause();
```
This page would be helpful: https://github.com/Splidejs/splide/issues/58

___

If you want to check whether the current slide has a video or not, the `active` event might be useful:
```javascript
splide.on( 'active', function( Splide ) {
  if ( /* check the Splide.slide class or data attribute */ ) {
    // the slide has video
  } else {
    // the slide has no video
  }
} );
```
It is triggered whenever the active slide is changed, providing the `Slide` object that contains the slide element.

**Comment by dannyvw** [comment]
@Splidejs Thanks for the information.
