### ISSUE TITLE
Youtube script is loaded when youtube is not used

### ISSUE THREAD

**Issue by mcolominas** [Splidejs/splide-extension-video#22]
Hi, I'm adding videos using the "data-splide-html-video" tag, but for some reason, it automatically loads me the following youtube scripts:
https://www.youtube.com/player_api
https://www.youtube.com/s/player/9f996d3e/www-widgetapi.vflset/www-widgetapi.js

Ideally, the scripts will be loaded once if the "data-splide-youtube" tag is present, and not make them always load (which I think is how it is done) or put some option to allow disabling it.

**Comment by NaotoshiFujita** [comment]
I've changed the logic and the extension will not load the script if there is no YouTube video.
