### ISSUE TITLE
Play button is empty (Accessibility Issue)

### ISSUE THREAD

**Issue by christopherjanzen** [Splidejs/splide-extension-video#27]
The overlay "Play" button is empty and currently just visual presentation. Adding an aria-label or hidden text would make this  accessible.

**Comment by christopherjanzen** [comment]
On further investigation, I suggest just making the button a "div" for now because the button element offers no functionality.

**Comment by NaotoshiFujita** [comment]
I'm not exactly sure what "no functionality" means, but I added an `aria-label` to the button in the latest build.
