### ISSUE TITLE
Wrong event for vimeo

### ISSUE THREAD

**Issue by dannyvw** [Splidejs/splide-extension-video#3]
https://github.com/Splidejs/splide-extension-video/blob/master/src/js/providers/vimeo/player.js#L35 is listening on an "end" event, but the documentation from vimeo says it must be "ended" (https://www.npmjs.com/package/@vimeo/player#ended)

**Comment by Splidejs** [comment]
Thanks! I've been fixed this.

**Comment by dannyvw** [comment]
@Splidejs Thanks for the quick fixes!
