### ISSUE TITLE
youtube videos cannot be played

### ISSUE THREAD

**Issue by dean224** [Splidejs/splide-extension-video#35]
Now it is found that all youtube videos cannot be played.
![image](https://user-images.githubusercontent.com/9065450/127608254-39583347-ad08-4979-acaa-3e179229d5ae.png)

**Comment by sgzadrian** [comment]
Check the PRs, the problem is that the extension adds an unnecessary attribute (`playlist`) into iframe options.
You can mitigate it adding `loop: true` to your video options

**Comment by dean224** [comment]
> Check the PRs, the problem is that the extension adds an unnecessary attribute (`playlist`) into iframe options.
> You can mitigate it adding `loop: true` to your video options

I tested it according to your method. Doesn't work at all
`<script>
    new Splide( '#videoslider', {
    	type   : 'loop',
    	loop: true,
    	heightRatio: 0.5625,
    	cover      : true,
    	lazyLoad   : 'sequential',
    	video: {
    		autoplay: true,
    		mute    : true,
    		disableOverlayUI:true,
    		hideControls:true,
    	},
    } ).mount( window.splide.Extensions );
</script>`

**Comment by kirtashy** [comment]
I have the same problem. This is a big bug because no youtube video has been working for days, not even on the example website it is working (https://splidejs.com/extension-video/). Until now I had used it on several websites and it worked correctly, but it no longer works anywhere

**Comment by dean224** [comment]
I found a solution
https://github.com/Splidejs/splide/issues/362
As for the above workaround, for cases where looping is undesired. Set the following player option to unset the playlist value:
`{
  video: {
    playerOptions: {
      youtube: {
        playlist: undefined,
      }
    }
  }
}`

**Comment by jlubeck** [comment]
> I found a solution
> [Splidejs/splide#362](https://github.com/Splidejs/splide/issues/362)
> As for the above workaround, for cases where looping is undesired. Set the following player option to unset the playlist value:
> `{ video: { playerOptions: { youtube: { playlist: undefined, } } } }`

using playlist: undefined didn't work for me. loop false did. Guess I'll live the loop
