### ISSUE TITLE
Muted attribute not added to html5 video element

### ISSUE THREAD

**Issue by pullasuti** [Splidejs/splide-extension-video#39]
If using muted :  true in the playerOptions for htmlVideo, the attribute is not added to the video element. The player will however mute the video, and most of the time things work. 

This will from time to time result with an error such as: 
Uncaught DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD

Should the muted attribute be explicitly set for the element somehow?

**Comment by NaotoshiFujita** [comment]
The `playerOptions` sets element properties, not attributes. and setting `muted` to `true` works for satisfying the browser autoplay policy.
You don't have to set the attribute manually.
