### ISSUE TITLE
Wrong event documentation

### ISSUE THREAD

**Issue by dannyvw** [Splidejs/splide-extension-video#4]
Documentation says it must be "video:ended" https://splidejs.com/extension-video/ but in the code it is "video:end" https://github.com/Splidejs/splide-extension-video/blob/master/src/js/providers/base/base-player.js#L257

Same for pause

**Comment by Splidejs** [comment]
Also fixed this. Here are correct names:

* video:play
* video:pause
* video:ended

Sorry for the inconvenience 😓
