### ISSUE TITLE
option to play video full width/height of slider (cover)

### ISSUE THREAD

**Issue by mi32dogs** [Splidejs/splide-extension-video#44]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

3.6.9

### Description

Is there an option or a way to play the video full width/height of slider (cover)?

### Steps to Reproduce

no steps

### Expected Behaviour

no behaviour

**Comment by NaotoshiFujita** [comment]
Use `width: '100vw', height: '100vh'`.

---
Closing this because this is just a question.
