### ISSUE TITLE
Splide-Extension-Video YouTube

### ISSUE THREAD

**Issue by BobbyShoe** [Splidejs/splide-extension-video#46]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

latest

### Description

After installing Splide-Extension-Video via npm I am getting this error when building my project.

error TS2688: Cannot find type definition file for 'youtube'.

1 /// <reference types="youtube" />
                        ~~~~~~~
Error: node_modules/@splidejs/splide-extension-video/dist/types/types/options.d.ts:37:19 - error TS2503: Cannot find namespace 'YT'.

37         youtube?: YT.PlayerVars;
              
Is there anything else that needs installed to make this work?

I have these imports included:
import { Splide } from '@splidejs/splide';
import { Video } from '@splidejs/splide-extension-video';
import '@splidejs/splide-extension-video/dist/css/splide-extension-video.min.css';

I am initializing a splide instance like this (this worked fine before adding the Video extension)
this.splide.mount({ Video });

This is an Angular 13 project.

Thanks.

### Reproduction Link

_No response_

### Steps to Reproduce

Use NPM to install video extension.
Include the video extension via the mount function.
Try to compile project.

### Expected Behaviour

Project compiles.

**Comment by NaotoshiFujita** [comment]
Mmm, can you try installing @types/youtube? You may also need @types/vimeo__player.

**Comment by BobbyShoe** [comment]
Thanks.  First pass looks like adding the @types/youtube fixed the building error.  Vimeo was needed, but may be later when Vimeo support is added.

**Comment by NaotoshiFujita** [comment]
Cool. I should mention that in the doc. Thanks.
