### ISSUE TITLE
IE11 SCRIPT5007 Error

### ISSUE THREAD

**Issue by moonspam** [Splidejs/splide-extension-video#48]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

v4.0.0

### Description

I'm used CDN version.
When splide-html-video start playing IE11, showing this error

> **SCRIPT5007: Unable to get value of the property 'catch': object is null or undefined**
> splide-extension-video.js (597,7)

### Steps to Reproduce

1. Include Splide and Video Extension CDN files
2. Include the library via the <script> tag
3. typed data-splide-html-video="MP4 URL"
4. Test page in IE11
...

### Expected Behaviour

Prevents errors from showing in IE11 Devtools Console Error

**Comment by NaotoshiFujita** [comment]
Hi, thank you for your report. I've fixed the issue in 0.7.1.

**Comment by moonspam** [comment]
I applied 0.7.1. and checked fix in IE11 👍
Thank you for responding quickly 😊
