### ISSUE TITLE
Youtube video player_api not loading

### ISSUE THREAD

**Issue by Schangiwalem** [Splidejs/splide-extension-video#49]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

v0.7.1

### Description

Hi everyone !

I use Splide exclusively on HTML static project with CDN inside HTML file.

When I want to try to load a Youtube video, that's doesn't work locally (localhost), player_api doesn't load on network console : 
![splide_video_player_notfound](https://user-images.githubusercontent.com/3245566/168335621-0bbbd794-8a49-41b9-9101-a114f8948731.png)
![splide_video_player_file_requested](https://user-images.githubusercontent.com/3245566/168335633-33bcc778-f212-4615-a63f-067a792e1cc0.png)

But when I deploy it on my cloudflare environment, so on web server, everything works correctly : 
![image](https://user-images.githubusercontent.com/3245566/168336016-4461be75-bf91-4425-8489-5e8c9edd573e.png)

I don't understand why that's calling a FILE when I try locally and a correct URL when I'm on web server.

Here the example I use to try : 

```
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.0.1/dist/css/splide.min.css" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@splidejs/splide-extension-video@0.7.1/dist/css/splide-extension-video.min.css" />
<script src="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.0.1/dist/js/splide.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@splidejs/splide-extension-video@0.7.1/dist/js/splide-extension-video.min.js"></script>
<div id="primary-slider" class="splide">
  <div class="splide__track">
    <ul class="splide__list">
      <li
        class="splide__slide"
        data-splide-youtube="https://www.youtube.com/watch?v=LJ7DU9Z3mNA"
      >
        <img src="assets/img/slider/slides/slide_mot2.jpg" />
      </li>
      <li
        class="splide__slide"
        data-splide-youtube="https://www.youtube.com/watch?v=cdz__ojQOuU"
      ></li>
      <li
        class="splide__slide"
        data-splide-youtube="https://www.youtube.com/watch?v=cdz__ojQOuU"
      ></li>
    </ul>
  </div>
</div>
<script>
  document.addEventListener("DOMContentLoaded", function () {
    var splide = new Splide("#primary-slider", {
      video: {
        autoplay: false,
        mute: false,
        loop: true,
        playerOptions: { youtube: { playlist: undefined } },
      },
    });
    splide.mount(window.splide.Extensions);
  });
</script>
```

Anyone has an explication please ? :)

### Steps to Reproduce

1. Use the HTML code I wrote on description inside an index.html file
2. Open it with CHROME directly
5. Click to play the video and open Network console.

### Expected Behaviour

When I click on the video's image on local version, video has to played correctly.

**Comment by NaotoshiFujita** [comment]
> Open it with CHROME directly

This does not work, since this extension is checking the protocol to correctly load the YouTube API. The local file protocol is `file:`
To check your code locally, open your HTML in your local server.

**Comment by Schangiwalem** [comment]
Thanks for your answer, that's clear for me.
However, create a local server just for a HTML project seems too much for me, but you're right that works ;)

**Comment by NaotoshiFujita** [comment]
Yes it's annoying, but no choice. Even if I forcibly set it to http or https, many videos say "Can not play the video".
