### ISSUE TITLE
Container option not working 

### ISSUE THREAD

**Issue by babobski** [Splidejs/splide-extension-video#52]
### Checks

- [X] Not a duplicate.
- [X] Not a question, feature request, or anything other than a bug report directly related to Splide. Use Discussions for these topics: https://github.com/Splidejs/splide/discussions

### Version

4.0.7

### Description

The container option is not working as aspected. It is only working if it's a direct child of the splide__slide.
For my design I have a slider with three columns inside the slide and I want to show the video in the center column.
Only I don't get it to work ( because it's not a direct child of the .splide__slide  ).

If I take a look at your code, it's pretty easy to make it work, so it's searches for the div inside of the splide__slide.
I have changed the code on:
https://github.com/Splidejs/splide-extension-video/blob/master/dist/js/splide-extension-video.js#L3388

From:
```javascript
    _proto6.init = function init() {
      var container = child(this.slide, "." + CLASS_CONTAINER);
      this.parent = container || this.slide;
      this.modifier = (container ? CLASS_CONTAINER : CLASS_SLIDE) + "--has-video";
      addClass(this.parent, this.modifier);
    };
```

To:
```javascript
    _proto6.init = function init() {
      var container = queryAll(this.slide, "." + CLASS_CONTAINER);
      this.parent = container[0] || this.slide;
      this.modifier = (container ? CLASS_CONTAINER : CLASS_SLIDE) + "--has-video";
      addClass(this.parent, this.modifier);
    };
```

And now it's working as aspected. 

### Steps to Reproduce

Place the video container in your splide__slide but not as direct child of the splide__slide

### Expected Behaviour

That the placement of the container element should not matter.

**Comment by NaotoshiFujita** [comment]
This is by design. The container element must be a direct child of the slide element.
Splide supports "nested" carousels, and therefore `queryAll` may incorrectly find containers of child or grand child carousels.
