### ISSUE TITLE
HTML5 Video black flash

### ISSUE THREAD

**Issue by andrej-pavlov** [Splidejs/splide-extension-video#7]
Hello,

thank you for your work on this plugin. 

The issue that i have is whenever i go to a slide that contains a html5 video, the slide image that i have set as a poster disappears for a second revealing a black frame, before the video starts to play. This happens only on page reload. Is there a workaround for this?

Thank you

here are my splide settings:

```
	new Splide( '#splide', { 	
        perPage    : 2,
        perMove: 1,
        height: '71vh',
        autoWidth: true,
        trimSpace: false,
        pagination: false,
        speed: 800,
        autoplay: true,
        type   : 'loop',
lazyLoad: 'sequential',
	video: {
		autoplay: true,
		mute    : true,
                loop: true,
                hideControls: true,
                disableOverlayUI: true
	},
}).mount(window.splide.Extensions ); 
```

**Comment by NaotoshiFujita** [comment]
I guess the video is buffering while the black frame is shown. The black frame is the background of the HTML video player.

1. Go to the slide
1. The video is requested to start
1. The poster is made hidden
1. The video starts buffering(<- the black frame)
1. The video starts

Normally, a loading icon is shown while buffering, but you hide it by `hideControls: true`.

How about preloading the video?
https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content

**Comment by andrej-pavlov** [comment]
Hello Naotoshi,

sorry for the late reply. Unfortunately either preloading the video with [<link rel="preload" href="video.mp4" as="video" type="video/mp4">](url) in <head> as with `hideControls: true` the situation is still the same...

**Comment by NaotoshiFujita** [comment]
Okay, thank you for the info.

I think it's too late but now the extension accepts `playerOptions`.
https://github.com/Splidejs/splide-extension-video#player-options

Using the `poster` attribute might solve the problem.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#attr-poster
