### ISSUE TITLE
Video functionality stops when destroy is triggered on splide element 

### ISSUE THREAD

**Issue by Autsider666** [Splidejs/splide-extension-video#8]
For starters, thanks a lot for al your work on both libraries.

We're having trouble converting a media wall (desktop) into a carousel(mobile) by using breakpoints to destroy the carousel on desktop. [Example](https://jsfiddle.net/dkLn0w15/4/)
Would there be a way to keep the splide video extension working while the rest of the functionality still gets disabled?

**Comment by NaotoshiFujita** [comment]
No, there is no way to do that. "destroy" destroys all functionalities of the slider, including the Video extension. If not, it's not "destroy".

The best way is to create a media wall(without Splide) and a carousel(with Splide) **individually**, and switch them by CSS media query.

**Comment by Autsider666** [comment]
You're right, that's what we were already expecting. Thanks for your time!
